baseURL = "https://dutlsl.github.io/"
title = "Deep Vision Insights"
theme = "PaperMod"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ko]
    languageName = "한국어"
    weight = 2

[params]
  env = "production"
  ShowTranslate = true # 언어 전환 토글 버튼 활성화

[params.math]
  enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$$', '$$'], ['$', '$']]